// Code generated by Wire. DO NOT EDIT.

package main

import (
	"context"

	"calculator-back/internal/handlers"
	"calculator-back/internal/log"
	"calculator-back/internal/service"
	"calculator-back/internal/telemetry"

	"github.com/gin-gonic/gin"
	"github.com/go-logr/logr"
)

func InitializeApp(ctx context.Context) (*gin.Engine, logr.Logger, func(context.Context) error, error) {
	logger := log.NewStdLogger()

	tracerProvider, shutdown, err := telemetry.NewTracerProvider(ctx, "calculator-back")
	if err != nil {
		return nil, logr.Logger{}, nil, err
	}

	calculatorService := service.NewCalculatorService()
	handler := handlers.NewCalcHandler(calculatorService, logger)
	router := newRouter(handler, logger, tracerProvider)

	return router, logger, shutdown, nil
}
