// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"calculator-back/internal/handler"
	"calculator-back/internal/log"
	"calculator-back/internal/service"
	"context"
)

// Injectors from wire.go:

func initializeApp(ctx context.Context) (*appComponents, error) {
	calculatorService := service.NewCalculatorService()
	calculatorHandler := handler.NewCalculatorHandler(calculatorService)
	logger := log.NewStdLogger()
	string2 := _wireStringValue
	mainTelemetryResources, err := newTelemetryResources(ctx, string2)
	if err != nil {
		return nil, err
	}
	tracerProvider := provideTracerProvider(mainTelemetryResources)
	engine := newRouter(calculatorHandler, logger, tracerProvider)
	v := provideTelemetryShutdown(mainTelemetryResources)
	mainAppComponents := newAppComponents(engine, logger, v)
	return mainAppComponents, nil
}

var (
	_wireStringValue = "calculator-back"
)
