// Code generated by MockGen. DO NOT EDIT.
// Source: calculator-back/internal/service (interfaces: CalculatorService)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_calculator.go -package=mocks calculator-back/internal/service CalculatorService
//

package mocks

import (
	reflect "reflect"

	domain "calculator-back/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockCalculatorService is a mock of CalculatorService interface.
type MockCalculatorService struct {
	ctrl     *gomock.Controller
	recorder *MockCalculatorServiceMockRecorder
	isgomock struct{}
}

// MockCalculatorServiceMockRecorder is the mock recorder for MockCalculatorService.
type MockCalculatorServiceMockRecorder struct {
	mock *MockCalculatorService
}

// NewMockCalculatorService creates a new mock instance.
func NewMockCalculatorService(ctrl *gomock.Controller) *MockCalculatorService {
	mock := &MockCalculatorService{ctrl: ctrl}
	mock.recorder = &MockCalculatorServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCalculatorService) EXPECT() *MockCalculatorServiceMockRecorder {
	return m.recorder
}

// Calculate mocks base method.
func (m *MockCalculatorService) Calculate(op domain.Operation, a, b float64) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Calculate", op, a, b)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Calculate indicates an expected call of Calculate.
func (mr *MockCalculatorServiceMockRecorder) Calculate(op, a, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Calculate", reflect.TypeOf((*MockCalculatorService)(nil).Calculate), op, a, b)
}
